### PR TITLE
Remove mono

### PR DESCRIPTION
**Pull request by mattwynne**
Ref https://github.com/cucumber/common/issues/1532

### CODE REVIEW

**Comment by mattwynne** [comment]
OK @aslakhellesoy this PR is fixed and ready to merge. Do you want to give the auto-release mechanism a spin and give me some feedback?

**Comment by aslakhellesoy** [comment]
I got an error at the step where I create a PR:

```
gh pr create --title "📦 Release v$VERSION" --body "See diff for details." --base release --head release-$VERSION


Creating pull request for release-0.5.0 into release in cucumber/build

pull request create failed: GraphQL error: No commits between release and release-0.5.0
```

**Comment by aslakhellesoy** [comment]
Looks like the `release-0.5.0` ended up in the wrong place when I was following the instructions:

Screenshot 2021-06-08 at 10 55 16

**Comment by aslakhellesoy** [comment]
Actually it failed higher up when I ran this:

```
git merge --squash v$VERSION

merge: v0.5.0 - not something we can merge
```

**Pull request merged**
