### PR TITLE
Add Dart

### PR DESCRIPTION
**Pull request by mattwynne**
Add Dart installation to main image

Ref: https://github.com/cucumber/common/pull/1630

### CODE REVIEW

**Comment by mattwynne** [comment]
I'm getting an error `E: Unable to locate package dart` when I run it locally on my M1 (arm64) Mac.

I tried fetching the file https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list and it appears to have an architecture flag of some sort on it:

```
deb [arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main
```

I wonder if that's the problem.

**Comment by mattwynne** [comment]
Maybe this can help: https://github.com/dart-lang/sdk/issues/26953#issuecomment-869216674

**Comment by lamkr** [comment]
Hi @mattwynne, I apologize again for taking a long time to respond, I'm pretty busy with my secular work.
I believe you solved the problem, am I right?

I built the docker image on my Mac 10.15 (intel) successfully. After, at bash of image, I called the command `dart` but it was not found. I added this line after calling the dart install script so it worked:

`ENV PATH "$PATH:/usr/lib/dart/bin"`

**note that I rename folder `dart-sdk` to `dart` during script running.

**Comment by mattwynne** [comment]
Yes, I think I have a working build image, bear with me while I get it released and we should see your PR go green!

**Pull request merged**
