### PR TITLE
Add GA build

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
Checks the image is buildable, will run on PRs, pushes and every night

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Note we could modify this to push the result at some point (if we pushed to github's container image repository it'd be a lot easier in terms of secrets management)

**Comment by mpkorstanje** [comment]
> Note we could modify this to push the result at some point (if we pushed to github's container image repository it'd be a lot easier in terms of secrets management)

Yes, but because of Cucumbers open model, literally anyone could then push anything. And we'd execute it during a release too.

**Comment by ciaranmcnulty** [comment]
@mpkorstanje It wouldn't necessarily have to be tagged as `cucumber build:latest` - that tagging could be an additional step

**Comment by mpkorstanje** [comment]
Currently only core team members can make releases. All core team members are trusted. So all artifacts are trusted. This is simple and easy to understand.

Once you allow CI to make any releases this reasoning becomes more nuanced. Artifacts released by CI can not be trusted to the same degree. I doubt we will be able to make the distinction without error.

And I'm saying this because for the past few months, just about every week now, I've had to explain to someone on the core team why making releases from a public CI would be fundamentally a bad idea. So collectively it is safe to say that have a hard time understanding security at a fundamental and conceptual level.

**Comment by mpkorstanje** [comment]
This isn't a complaint about the current PR btw. I'm only critiquing the suggestion that we could publish these images automatically.

**Comment by ciaranmcnulty** [comment]
We could have the docker push action happen on ‘release’ in that case

**Comment by mpkorstanje** [comment]
We don't distinguish between core and all the other committers, so anything the core uses to trigger a release can be used by anyone.

**Comment by ciaranmcnulty** [comment]
@mpkorstanje i must have misunderstood ‘ Currently only core team members can make releases’. Will try and catch you on slack

**Comment by aslakhellesoy** [comment]
Hi @ciaranmcnulty,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
