### PR TITLE
Fix permisisons issue

### PR DESCRIPTION
**Pull request by mattwynne**
In https://github.com/cucumber/common/pull/1847 we have an issue with the build image not seeming to give the cukebot user sufficient permissions.

I've started by extending the acceptance tests script to reproduce this problem. It seems that the `/app` folder isn't writable by the `cukebot` user anymore(!) so I've added a line to the `Dockerfile` to fix that.

This branch is a space to play around with the problem.

### CODE REVIEW

**Comment by mattwynne** [comment]
I am testing a theory that all the stuff we were doing to create a user is unnecceary, and we can just run as the default root user. This should simplify things.

**Comment by mattwynne** [comment]
I've tested this locally and I'm pretty confident it's going to work. I'm going to release it.

**Comment by gaeljw** [comment]
FYI I had to make some changes on cucumber-jvm-scala release process to handle the new image: https://github.com/cucumber/cucumber-jvm-scala/pull/262/files.

I'm surprised @mpkorstanje didn't need to in cucumber-jvm, maybe you were still using a previous version of the Docker image?

**Comment by mpkorstanje** [comment]
Cucumber JVM has pinned the image to a specific version.

https://github.com/cucumber/cucumber-jvm/blob/main/Makefile#L78

**Comment by gaeljw** [comment]
I actually noticed some undesired side effects, I did not have time to look more into the details but for cucumber-jvm-scala mounting some folders in the container with the `root` user make them owned by `root` in the host system which is clearly not good.

This wasn't happening with the cukebot user before, so maybe it's not entirely related to the root user.

**Comment by mattwynne** [comment]
Interesting, thanks for the heads-up @gaeljw.

Do you use the docker container for day-to-day development, or just for making releases?

If we were to move you over to using [automated releases](https://github.com/cucumber/common/issues/1688), would you need to use this container at all anymore?

**Comment by gaeljw** [comment]
@mattwynne I use it only for making releases. Moving to the automated process would be very much better and would indeed remove the need for the container :)

**Pull request merged**
